yarnPath: .yarn/releases/yarn-3.3.1.cjs

nodeLinker: node-modules
enableGlobalCache: true
enableInlineBuilds: true 

npmScopes:
  idwall:
    npmPublishRegistry: "https://artifacts.idwall.services/repository/sdk-npm-releases/"
    npmRegistryServer: "https://artifacts.idwall.services/repository/sdk-npm-releases/"
    npmAlwaysAuth: true
    npmAuthIdent: "ZWR1YXJkb19zaWx2YV9vbW5pOmVkdWFyZG8lME1OMSU="
